### ISSUE TITLE
Update to RHOAI 2.10

### ISSUE THREAD

**Issue by mamurak** [RedHatQuickCourses/rhods-model#12]
The RHOAI dashboard has been reworked after version 2.8. As for the more recent RHOAI version the screenshots in the [setup](https://redhatquickcourses.github.io/rhods-model/rhods-model/1.33/chapter2/section1.html) section are outdated and need to be updated.

**Comment by kknoxrht** [comment]
screenshots replaced with updated using latest stable RHOAI 2.11.  

merged in this pull request:  https://github.com/RedHatQuickCourses/rhods-model/pull/14
